import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-[#f5f5f5] dark:bg-[#0b0d0e]`}>
          <Providers>
						<main className="p-6 min-h-[100svh]">{children}</main>
					</Providers>
			</body>
		</html>
	);
}
